- README.md
- neuraxle/base.py
- neuraxle/hyperparams/space.py
- neuraxle/steps/util.py
Main content of the first documentation page in the table of content.
> Update website's documentation

- .clabot
- README.rst
> Adding contributors

- README.rst
https://gitter.im/Neuraxle/community
> Added Gitter channel to project.

- neuraxle/base.py
Minimal changes were made: a careful refactor of TruncableSteps could be interesting for the refresh function (perhaps not needed anymore: it's just that slicing will need to loop and dynamically compute names each time it needs a slice or to access a particular step perhaps).
@alexbrillant Don't hesitate to add commits to this branch before merging to refactor if you think a refactor is needed, etc.
> Added names as a BaseStep property as suggested by @alexbrillant 

- neuraxle/hyperparams/distributions.py
> Fix https://github.com/Neuraxio/Neuraxle/issues/31

- neuraxle/base.py
- neuraxle/hyperparams/space.py
- testing/test_pipeline.py
> Fix https://github.com/Neuraxio/Neuraxle/issues/24

- setup.py
Removing Keras and TensorFlow for now, as they are unused (and not even in requirements.txt). 
Note: not sure to what happened with the order of the imports.
> Removed unused dependencies.

- neuraxle/base.py
- neuraxle/pipeline.py
- testing/test_metastep_mixin.py
- testing/test_truncable_steps.py
Add set_train method to BaseStep, and TruncableSteps. 
In the transform functions, you can add a simple if statement to direct to the right implementation:
```
def transform(self, data_inputs):
if self.train:
self.transform_train_(data_inputs)
else:
self.transform_test_(data_inputs)
def fit_transform(self, data_inputs, expected_outputs):
if self.train:
self.fit_transform_train_(data_inputs, expected_outputs)
else:
self.fit_transform_test_(data_inputs, expected_outputs)
```
> Add train/test mode in BaseStep, And TruncableSteps 

- neuraxle/base.py
- neuraxle/checkpoints.py
- neuraxle/pipeline.py
@alexbrillant please read carefully all of the suggested changes.
> Pseudocode on how to save steps independently from each other after stripping.

- neuraxle/base.py
- neuraxle/pipeline.py
- neuraxle/steps/flow.py
- neuraxle/steps/misc.py
- testing/steps/neuraxle_test_case.py
- testing/steps/test_choose_one_or_many_steps_of.py
- testing/steps/test_choose_one_step_of.py
- testing/steps/test_train_only_wrapper.py
- TrainOnlyWrapper : wrapper to execute wrapped step only in train (or test if is_train parameter is to False)
- Introduce Reusable NeuraxleTestCase class for better unit tests
```
p = Pipeline([
TrainOnlyWrapper(Identity())
])
p = Pipeline([
TrainOnlyWrapper(Identity(), test_only=False)
])
```
> Implement TrainOnlyWrapper

- neuraxle/hyperparams/distributions.py
- neuraxle/metaopt/auto_ml.py
My pull request does: 
Fix Boolean RVS return type. 
Fix invalid json file loading in HyperparamsJsonRepository.
> Fix bug automl boolean

- neuraxle/union.py
My pull request does: fix the default joiner
> Fix default joiner reference in FeatureUnion

- neuraxle/steps/sklearn.py
#119 What it is
My pull request does: 
add partial fit argument to the sklearnwrapper so that it calls partial fit when its set to True
> Add partial fit support to Neuraxle SKLearnWrapper

- .github/workflows/testpythonpackage.yml
- neuraxle/hyperparams/distributions.py
- neuraxle/metaopt/random.py
- setup.py
- testing/metaopt/test_automl_sequential_wrapper.py
- testing/metaopt/test_tpe.py
Setting seeds in a few test, replacing python's random by numpy.random as to make it more straightforward to do reproducible experiments, added scikit in dependencies, added python 3.8 in build.
> Dependencies adjustment, build extended to 3.8, extended usage of np.random

- examples/getting_started/plot_force_handle_mixin.py
- testing/examples/test_examples.py
We realised some tests were missing in test_examples when recompiling the doc. This PR adds test for all examples and fixes the only test which was not passing. (fix #449)
> Added test for all examples and fixed plot_force_handle_mixin

- examples/Handler Methods.ipynb
- examples/Step Saving And Lifecycle.ipynb
- neuraxle/base.py
- neuraxle/data_container.py
- neuraxle/metaopt/auto_ml.py
- neuraxle/metaopt/deprecated.py
- neuraxle/pipeline.py
An update of docstrings and notebook examples in prevision of the rebuilding of the website to version 0.5.7.
> Documentation update

- neuraxle/steps/loop.py
My pull request does: 
Add Break, and Continue steps to be used inside the ForEachDataInput step and MiniBatchSequentialPipeline.  
Here is how you can use this new code as a end user: 
`ForEachDataInput(Break(data_container_is_full), Continue(data_container_is_empty))`
> Add Continue & Break Steps For MiniBatchSequentialPipeline & ForEachDataInput

- .clabot
> Adding Rohith295 to contributors

- neuraxle/distributed/streaming.py
- testing/test_streaming.py
My pull request does: fixes issue #506
> fix teardown problem in StreamingQueuePipeline

- .github/workflows/testpythonpackage.yml
- examples/sklearn/plot_boston_housing_meta_optimization.py
- examples/sklearn/plot_cyclical_feature_engineering.py
- neuraxle/base.py
- neuraxle/metaopt/auto_ml.py
- neuraxle/steps/column_transformer.py
- setup.py
- testing/examples/test_examples.py
- testing/steps/test_column_selector_2d.py
Add a time series processing example. 
Adapted this one: 
https://scikit-learn.org/stable/auto_examples/applications/plot_cyclical_feature_engineering.html
See plot_cyclical_feature_engineering.py!
__________________
Things to check each time you contribute:
> Add cyclical feature engineering example and Fix 168.
